### ISSUE TITLE
Image cropping

### ISSUE THREAD

**Issue by Varzeki** [Varzeki/Homescreens#1]
Some thumbnails incorrectly display as empty and will require manual cropping to 500x500

**Comment by inexist3nce** [comment]
i hated everything about your script and `out.gen` so i went ahead and redid the whole thing

the `imagegen.rb` was recreated (https://github.com/Varzeki/Homescreens/commit/3bf54bd4e33d2fb15274878b1e6ca6b1acb34dfc) to grab every folder inside `data/` that contains something, generate some html, and write it to `screens.html`. also i dont know how to ruby so its probably broken or weird.

folder structure (https://github.com/Varzeki/Homescreens/commit/e44a40355ee02d743ac4719ba478855187cb3e9a and https://github.com/Varzeki/Homescreens/commit/7518a1de8bd53238339d6fa1f159b7d8e9c45186) before:

    site/
     |--- css
     |--- fonts
     `--- images
       |--- full
       |--- webm
       `--- thumb_sq
          `--- contains 23 thumbnails (half were zero-byte files)

now:

    site/
     |--- css
     |--- fonts
     `--- data
       `--- N
          `--- contains original image also a 400x COMPRESSED png

changes:
- removed old thumbnails (https://github.com/Varzeki/Homescreens/commit/c2f7df877881f7bbcbd9dbe0b2c0802dabd6b532)
- contemplated the lack of automatization in steps that took the user more than a minute
- added new thumbnails: 400x400 optimized and compressed for all of the 93 uploaded images (https://github.com/Varzeki/Homescreens/commit/77b368742e5f2ef3c0cebbde14482158dfc65ea6)

issues:
- i cannot figure out at all how to deal with video files, so they sit in `images/webm/` without any changes

kthxbai
